[package]
name = "next-transform-dynamic"
version = "0.1.0"
description = "SWC transform for next/dynamic"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

[dependencies]
pathdiff = { workspace = true }
turbo-binding = { workspace = true, features = [
  "__swc_core_next_core",
]}

[dev-dependencies]
turbo-binding = { workspace = true, features = [
  "__swc_core_testing_transform",
]}
testing = { workspace = true }
