[package]
name = "next-font"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"

[lib]
bench = false

[dependencies]
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
turbo-binding = { workspace = true, features = ["__swc_core_next_core"] }
