on:
  push:
    branches: [ijjk/test-buildjet]

name: Build, test, and deploy

env:
  NAPI_CLI_VERSION: 2.13.3
  TURBO_VERSION: 1.6.3
  RUST_TOOLCHAIN: nightly-2022-11-04
  PNPM_VERSION: 7.24.3
  PLAYWRIGHT_VERSION: 1.28.1
  NODE_LTS_VERSION: v18
  NODE_PREV_VERSION: v16

jobs:
  # pre-populate turbo build cache so we don't duplicate effort
  # and avoid leveraging actions/cache
  build:
    runs-on: buildjet-16vcpu-ubuntu-2204
    env:
      NEXT_TELEMETRY_DISABLED: 1
      # we build a dev binary for use in CI so skip downloading
      # canary next-swc binaries in the monorepo
      NEXT_SKIP_NATIVE_POSTINSTALL: 1
      TURBO_TEAM: 'vercel'
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_REMOTE_ONLY: 'true'
    steps:
      # Start with LTS for build and initial tests
      - name: Setup node LTS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true

      - run: node -v
        name: print Node.js version

      - run: npm i -g "pnpm@${PNPM_VERSION}" "@napi-rs/cli@${NAPI_CLI_VERSION}" "turbo@${TURBO_VERSION}"
        name: install npm packages

      - uses: actions/checkout@v3
        name: checkout repo
        with:
          # we use an arbitrary depth to have some history to check for
          # related changes e.g. docs only changes
          fetch-depth: 15

      - run: pnpm install
        name: install dependencies

      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain "${RUST_TOOLCHAIN}"
        name: Setup rustup

      - run: rustup target add x86_64-unknown-linux-gnu && unset CC_x86_64_unknown_linux_gnu && unset CC && pnpm build-ci && strip packages/next-swc/native/next-swc.*.node
        name: Build

      # TODO: re-enable after fixing potential concurrency issue https://github.com/vercel/next.js/actions/runs/4062773116/jobs/7004366709#step:10:479
      # - run: pnpm lint
      #   name: Run lint checks

  test:
    strategy:
      fail-fast: false
      matrix:
        type: [dev, devE2E, start, startE2E, integration]
    runs-on: buildjet-16vcpu-ubuntu-2204
    needs: build
    env:
      NEXT_TELEMETRY_DISABLED: 1
      # we build a dev binary for use in CI so skip downloading
      # canary next-swc binaries in the monorepo
      NEXT_SKIP_NATIVE_POSTINSTALL: 1
      TURBO_TEAM: 'vercel'
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_REMOTE_ONLY: 'true'
    steps:
      # Start with LTS for build and initial tests
      - name: Setup node LTS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true

      - run: node -v
        name: print Node.js version

      - run: npm i -g "pnpm@${PNPM_VERSION}" "@napi-rs/cli@${NAPI_CLI_VERSION}" "turbo@${TURBO_VERSION}"
        name: install npm packages

      - uses: actions/checkout@v3
        name: checkout repo
        with:
          # we use an arbitrary depth to have some history to check for
          # related changes e.g. docs only changes
          fetch-depth: 15

      - run: pnpm install
        name: install dependencies

      - run: pnpm dlx "playwright@${PLAYWRIGHT_VERSION}" install-deps && pnpm dlx "playwright@${PLAYWRIGHT_VERSION}" install
        name: setup playwright dependencies

      - run: pnpm build-ci && strip packages/next-swc/native/next-swc.*.node
        name: Build

      - run: node run-tests.js -c 16 --type development
        if: ${{ matrix.type === 'dev' }}
        name: Test dev

      - run: node run-tests.js -c 16 --type production
        if: ${{ matrix.type === 'start' }}
        name: Test start

      # we run this along with the fastest group which is
      # currently test/production
      - run: pnpm test-browsers
        if: ${{ matrix.type === 'start' }}
        name: Test Firefox and Safari

      - run: NEXT_TEST_MODE=dev node run-tests.js -c 16 --type e2e
        if: ${{ matrix.type === 'devE2E' }}
        name: Test dev E2E

      - run: NEXT_TEST_MODE=start node run-tests.js -c 16 --type e2e
        if: ${{ matrix.type === 'startE2E' }}
        name: Test start E2E

      - run: node run-tests.js -c 16
        if: ${{ matrix.type === 'integration' }}
        name: Test integration
